# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d1a18412ef345a8bc6e7140da91d18cb1f281fd3891ae938231e3b59a3aed8480c355c832d60a0e52c360b06b396ff26dff77122b68ef96288a71aa7a1e47328

test:
  secret_key_base: ec59b68d14f4dc311c92bb6804837e60b1b1ce73549273d5c356e1a6fba7f749f151b0ca36e1bb0da7a049e36557a8943845f77de991370b5fb30644b511e397

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
